ACTIVITY_LOG_MSG = "%s HAS BEEN WITHDRWN FROM ACCOUNT: %s"
ACTIVITY_DEPOSIT = "WALLET DEPOSIT OF %s HAS BEEN MADE BY CUSTOMER: %s "
ACTIVITY_TRANSFER = "%s HAS BEEN MOVED FROM: %s TO BENEFICIARY: %s"
